name: "Deploy artifact to SWA"

inputs:
  AZURE_STATIC_WEB_APPS_API_TOKEN:
    required: true
  REPO_TOKEN:
    required: 
    
env:
  ARTIFACT_TO_UPLOAD_PATH: $GITHUB_WORKSPACE/artifact-to-upload

runs:
  using: "composite"

  steps:
    - uses: actions/download-artifact@v4
      with:
        name: WebApp
        path: $ARTIFACT_TO_UPLOAD_PATH

    - uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ inputs.REPO_TOKEN }}
        action: "upload"
        skip_app_build: true
        skip_api_build: true
        output_location: ''
        app_location: $ARTIFACT_TO_UPLOAD_PATH
