name: "Deploy"

inputs:
  AZURE_STATIC_WEB_APPS_API_TOKEN:
    required: true
  REPO_TOKEN:
    required: true

runs:
  using: "composite"
    - uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ inputs.REPO_TOKEN }}
        skip_app_build: true
        action: "upload"
